---

# Copy yaml file with all the config to deploy Jenkins to the remote server
- name: Copy jenkins.yaml to remote
  copy:
    src: jenkins.yaml
    dest: /tmp/jenkins.yaml
    follow: no

# Change the previously copied file to use the nfs server ip declared in jenkins_vars file
- name: Change nfs server ip
  replace:
    path: /tmp/jenkins.yaml
    # Find the line with the value of the nfs server ip
    regexp: '(server:)(.*)'
    # Change the net value of the previous line
    replace: '\1 "{{ nfs_server_ip }}"'

# Delete jenkins namespace to avoid problems redeploying the app
- name: Delete Jenkins namespace
  command: kubectl delete namespace jenkins
  register: 
  # Do not fail if namespace does not exists
  failed_when: namespace_exists.rc == 2
  become: yes
  # Use the kubeadmin user to execute the comand
  become_user: kubeadmin

# Delete jenkins persistentvolumes to avoid problems redeploying the app
- name: Delete Jenkins persistentvolumes
  command: kubectl delete persistentvolumes jenkins-pv
  register: persistentvolumes_exists
  # Do not fail if persistent volume does not exists
  failed_when: persistentvolumes_exists.rc == 2
  become: yes
  # Use the kubeadmin user to execute the comand
  become_user: kubeadmin

# Create jenkins namespace
- name: Create Jenkins namespace
  command: kubectl create namespace jenkins
  become: yes
  become_user: kubeadmin

# Deploy jenkins app using the yaml file
- name: Deploy jenkins app
  command: kubectl apply -f /tmp/jenkins.yaml
  become: yes
  become_user: kubeadmin
