---

# Open the ports defined in kubeadmin_vars file
- name: Open {{ kubeadmin_ports }} ports
  firewalld:
    port: "{{ item }}"
    # Persist change between reboots
    permanent: yes
    # Open the ports
    state: enabled
    # Make changes available immediately
    immediate: yes
  become: yes
  with_items: "{{ kubeadmin_ports }}"
