---

- name: Create user kubeadmin
  user:
    name: kubeadmin
    password: "{{ kubeadmin_password }}"
  become: yes

- name: Create .kube directory
  file:
    path: /home/kubeadmin/.kube
    state: directory
  become: yes

- name: Copy admin.conf to kubeadmin's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeadmin/.kube/config
    # Execute the command in the master machine not in the ansible controller
    remote_src: yes
  become: yes

- name: Give kubeadmin permissions to amdin.conf file
  file:
    path: /root/.kube/config
    owner: kubeadmin
  become: yes
