---

# Open the ports defined in nfs_vars file
- name: Open {{ nfs_ports }} ports
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
  with_items: "{{ nfs_ports }}"
