---

# Use the timezone set in common_vars file
- name: Set timezone to {{ timezone }}
  timezone:
    name: "{{ timezone }}"
  become: yes

- name: Install chrony
  dnf:
    name: "chrony"
    state: latest
  become: yes

- name: Enable and start service chrony
  systemd:
    name: chronyd
    state: started
    enabled: yes    
  become: yes

- name: Enable ntp
  command: 
    cmd: /usr/bin/timedatectl set-ntp true
  become: yes
