---

- name: Disable SELinux
  selinux:
    state: disabled
  register: result
  become: yes

- name: Reboot the machine
  reboot:
  become: yes
  # Only reboot when required by selinux command
  when: result.reboot_required|bool
