---

- name: Enable and start service firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  become: yes

- name: Set AllowZoneDrifting to 'no' to avoid security concerns
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    # Find the line matchin this regexp
    regexp: 'AllowZoneDrifting'
    # Replace all the matched line with this value
    line: 'AllowZoneDrifting=no'
    backrefs: yes
  register: result
  become: yes

- name: Reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
  become: yes
  # Reload firewalld config only when the previous command change the state
  when: result.changed|bool
