---

# Open the ports declared in the file kubeworker_vars
- name: Open {{ kubeworker_ports }} ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
  with_items: "{{ kubeworker_ports }}"
