---

 - name: Allow worker access to master
   firewalld:
     rich_rule: rule family=ipv4 source address="{{ inventory_hostname }}"/32 accept
     permanent: yes
     state: enabled
     immediate: yes
   become: yes
   delegate_to: "{{ item }}"
   with_items: "{{ groups['master'] }}"  
