---

- name: Get join command from master
  command: kubeadm token create --print-join-command
  delegate_to: "{{ item }}"
  register: join_command
  become: yes
  with_items: "{{ groups['master'] }}"

- name: Reset kubeadm
  command: kubeadm reset -f
  become: yes

- name: Join worker to masters
  command: "{{ item.stdout }}"
  with_items: "{{ join_command.results }}"
  become: yes
