---

- name: Configure worker
  hosts: all
  gather_facts: false
  vars_files:
    - "group_vars/common_vars.yaml"
    - "group_vars/kubecommon_vars.yaml"
    - "group_vars/kubeworker_vars.yaml"
  roles:
    - common
    - kubecommon
    - kubeworker
