---

# Use the sysctl module to enable the property
- name: Set net.bridge.bridge-nf-call-ip6tables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    state: present
  become: yes

# Use the sysctl module to enable the property
- name: Set net.bridge.bridge-nf-call-iptables to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
  become: yes
