---

# Open the ports declared in the file kubecommon_vars
- name: Open {{ azure_sdn_ports }} port
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  become: yes
  with_items: "{{ azure_sdn_ports }}"
